version: '3.9'

services:
  solid-server-verkoper:
    build: ./
    command: -p 3001 -c config-mashlib.json -f /data
    ports:
        - 3001:3001
    volumes:
        - ./solid-server-verkoper/data:/data

  solid-server-koper:
    build: ./
    command: -p 3002 -c config-mashlib.json -f /data
    ports:
        - 3002:3002
    volumes:
        - ./solid-server-koper/data:/data
