version: '3.9'

services:
  koopovereenkomst-app:
    build:
      context: koopovereenkomst-v3-simple
    ports:
      - 3000:3000
      
  koopovereenkomst-server:
    build:
      context: koopovereenkomst-server
    environment:
      - VC_API_URL=http://koopovereenkomst-vc-api:8081
    ports:
      - 8080:8080

  koopovereenkomst-vc-api:
    build:
      context: koopovereenkomst-vc-api
    ports:
      - 8081:8081

  solid-pod-provider:
    build:
      context: community-server
    command: -p 3001
    environment:
      - CSS_ROOT_FILE_PATH=/data
    ports:
      - 3001:3001
    volumes:
      - ./solid-pod-provider/data:/data
